name: dotnet package test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0','3.1.x','5.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Display dotnet version
        run: dotnet --version
