name: dotnet package test

on: [push]

jobs:
  build:

    runs-on: [windows-latest,linux]
    strategy:
      matrix:
        dotnet-version: ['3.0','3.1.x','5.0.x']
    
      steps:
      - name: Display dotnet version
        run: dotnet --version
